package org.team1.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "EService", targetNamespace = "http://eservice/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
        ObjectFactory.class
})
public interface EService {


    /**
     * @param arg0
     * @return returns client.BaseResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://eservice/EService/getZoomLinkRequest", output = "http://eservice/EService/getZoomLinkResponse")
    public BaseResponse getZoomLink(
            @WebParam(name = "arg0", partName = "arg0")
                    BaseRequest arg0);

}
