package org.team1.client;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "EServiceImplService", targetNamespace = "http://eservice/", wsdlLocation = "http://172.25.112.1:7777/ws/eservice?wsdl")
public class EServiceImplService
        extends Service {

    private final static URL ESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName ESERVICEIMPLSERVICE_QNAME = new QName("http://eservice/", "EServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.25.112.1:7777/ws/eservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        ESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public EServiceImplService() {
        super(__getWsdlLocation(), ESERVICEIMPLSERVICE_QNAME);
    }

    public EServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ESERVICEIMPLSERVICE_QNAME, features);
    }

    public EServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, ESERVICEIMPLSERVICE_QNAME);
    }

    public EServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ESERVICEIMPLSERVICE_QNAME, features);
    }

    public EServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (ESERVICEIMPLSERVICE_EXCEPTION != null) {
            throw ESERVICEIMPLSERVICE_EXCEPTION;
        }
        return ESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns EService
     */
    @WebEndpoint(name = "EServiceImplPort")
    public EService getEServiceImplPort() {
        return super.getPort(new QName("http://eservice/", "EServiceImplPort"), EService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns EService
     */
    @WebEndpoint(name = "EServiceImplPort")
    public EService getEServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://eservice/", "EServiceImplPort"), EService.class, features);
    }

}
